### ISSUE TITLE
mastodon-streaming.service のエラー!?

### ISSUE THREAD

**Issue by hamaguchi** [kibousoft/mastodon#4]
AWSではなく、さくらのVPS(Ubuntu)で動かしているのですが、以下の様なエラーが出ています。

```
 4月 21 21:46:14 monza npm[17830]: info Starting streaming API server worker on port 4000
 4月 21 21:46:24 monza npm[17830]: /home/makoto/sites/mastodon/node_modules/pg/lib/connection.js:121
 4月 21 21:46:24 monza npm[17830]:       self.emit(msg.name, msg);
 4月 21 21:46:24 monza npm[17830]:                    ^
 4月 21 21:46:24 monza npm[17830]: TypeError: Cannot read property 'name' of undefined
 4月 21 21:46:24 monza npm[17830]:     at Socket.<anonymous> (/home/makoto/sites/mastodon/node_modules/pg/lib/connection.js:121:20)
 4月 21 21:46:24 monza npm[17830]:     at emitOne (events.js:96:13)
 4月 21 21:46:24 monza npm[17830]:     at Socket.emit (events.js:188:7)
 4月 21 21:46:24 monza npm[17830]:     at readableAddChunk (_stream_readable.js:176:18)
 4月 21 21:46:24 monza npm[17830]:     at Socket.Readable.push (_stream_readable.js:134:10)
 4月 21 21:46:24 monza npm[17830]:     at TCP.onread (net.js:551:20)
 4月 21 21:46:24 monza npm[17830]: ERR! Worker died with exit code 1, signal null received.

```

たぶん、gitのmasterブランチだと思われます。解決しますか!?

**Comment by ANNotunzdY** [comment]
@hamaguchi エラー報告ありがとうございます。
node.js側について、pgからmysqlに書き換え忘れていたのが原因です。。
こちらでも再現できましたので、確認・対応します。

**Comment by ANNotunzdY** [comment]
@hamaguchi 
不具合について修正後、Streaming API（/api/v1/streaming/public）にアクセスし動作することを確認いたしました。
masterブランチにPush済みです。よろしくお願い致します。
